#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wmakeLnInclude fuelCellSystems

wmake $targetType regionCourantNo
wmake $targetType interfacialModels
wmake $targetType interfacialCompositionModels
wmake $targetType derivedFvPatchFields
wmake $targetType functionObjects
wmake $targetType multiPhaseCompressibleTurbulenceModels
wmake $targetType fuelCellSystems

#------------------------------------------------------------------------------
