#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf \
    constant/*/polyMesh \
    constant/polyMesh \
    [0-9]*/cellToRegion \
    [0-9]*/[afiep]/cellToRegion \
    constant/cellToRegion \
    constant/[a-z]*/cellToRegion \
    constant/[a-z]*/[Tk]

#------------------------------------------------------------------------------
