#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso fuelCellSystem
wclean libso regionCourantNo
wclean libso multiPhaseCompressibleTurbulenceModels

#------------------------------------------------------------------------------
