#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso interfacialModels
wclean libso interfacialCompositionModels
wclean libso derivedFvPatchFields
wclean libso functionObjects
wclean libso fuelCellSystem
wclean libso multiPhaseCompressibleTurbulenceModels

#------------------------------------------------------------------------------
