#!/bin/sh
cd ${0%/*} || exit 1 # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf \
    constant/*/polyMesh \
    constant/polyMesh \
    [0-9]*/cellToRegion \
    [0-9]*/[a-z]*/cellToRegion \
    constant/cellToRegion \
    constant/[a-z]*/cellToRegion \
    constant/[a-z]*/[Tk]* \
    constant/[a-z]*/cellID \
    constant/cellID \
    [0] \
    salome.unv

#------------------------------------------------------------------------------
